[pytest]
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
# Ignore deprecation warnings to keep outputs extremely clean
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
